- herokux/resource_herokux_formation_autoscaling.go
The `PATCH` call returns a 403 with no information.
> Optimize error handling when autoscaling a non scalable dyno formation 

- api/examples/kafka/main.go
- api/kafka/consumer_groups.go
- api/kafka/helper.go
- api/kafka/helper_test.go
- api/kafka/kafka-accessors.go
- api/kafka/topics.go
- api/kafka/types.go
- go.mod
- go.sum
- herokux/config.go
- herokux/import_herokux_kafka_topic_test.go
- herokux/provider.go
- herokux/resource_herokux_kafka_consumer_group.go
- herokux/resource_herokux_kafka_topic.go
- herokux/resource_herokux_kafka_topic_test.go
- website/docs/index.html.markdown
- website/docs/r/kafka_topic.html.markdown
- website/herokux.erb
- Topic name is not updateable.
- `retention_time_ms` needs to be in the PUT body for multi-tenanted plans.
- `partitions` is not editable after creation.
- Retention is required when compaction is disabled.
- Retention time must be set for multi-tenanted plans.
- The replication factor of the topic. Must be 3 for this plan.
- Retention time min value is 24 hours. Max depends on the plan.
- it takes time for the topics to be created and the partitions ready
https://devcenter.heroku.com/articles/multi-tenant-kafka-on-heroku#basic-plans
> New resource: `herokux_kafka_topic`

- api/postgres/types.go
- herokux/resource_herokux_postgres_mtls.go
There seems to be a quirk in the GET endpoint for MTLS where it sometimes returns a 500. The provisioning still is processing so the provider should try again to check its status.
> mtls handle 500s by retrying

- api/api.go
- api/data/types.go
- api/kafka/cluster.go
- api/kafka/consumer_groups.go
- api/kafka/topics.go
- api/postgres/mtls.go
- api/postgres/mtls_cert.go
- api/postgres/mtls_iprule.go
- api/postgres/postgres-accessors.go
- api/postgres/privatelink.go
- helper/test/config.go
- helper/test/helper.go
- herokux/config.go
- herokux/helpers.go
- herokux/import_herokux_privatelink_test.go
- herokux/provider.go
- herokux/resource_herokux_privatelink.go
- herokux/resource_herokux_privatelink_test.go
- website/docs/index.html.markdown
- website/docs/r/privatelink.html.markdown
- website/herokux.erb
- Resource can be used for Kafka, Postgres, and Redis.
- Initial `POST` and UI requires a valid AWS account ID but it can be removed afterwards.
> New resource: herokux_privatelink

- api/api.go
- api/postgres/database.go
- api/postgres/postgres-accessors.go
- api/postgres/postgres.go
- api/postgres/types.go
- herokux/config.go
- herokux/provider.go
- herokux/resource_herokux_postgres.go
- herokux/resource_herokux_postgres_test.go
- website/docs/index.html.markdown
This pull request aims to replicate a leader + follower postgres database [setup](https://devcenter.heroku.com/articles/heroku-postgres-follower-databases#create-a-follower).
- Only can create one leader and one follower.
- This resource would not necessarily replace `heroku_addon` as version one is very basic.
- provider block that controls the `last commit behind before unfollowing`.
- promote vs unfollow | unfollow vs promote.
- This resource requires the following polling mechanisms:
- poll when the leader db is provisioned
- poll when the follder db is provisioned (if applicable)
- poll when the leader db is ready for followers
- poll when the follower db is caught up with the leader for promotion
- when the follower is `waiting?` set to `false` and `status` set to Available. …
> (WIP) New resource herokux_postgres

- api/postgres/credential.go
- api/postgres/postgres-accessors.go
- api/postgres/types.go
- herokux/config.go
- herokux/import_herokux_postgres_credential_test.go
- herokux/provider.go
- herokux/resource_herokux_kafka_topic.go
- herokux/resource_herokux_postgres_credential.go
- herokux/resource_herokux_postgres_credential_test.go
- website/docs/index.html.markdown
- website/docs/r/postgres_credential.html.markdown
- website/herokux.erb
https://devcenter.heroku.com/articles/heroku-postgresql-credentials
New resource CREATE & DELETE only. There's no update. The permissions is backed by GRAPHQL so a bit tricky.
```hcl
resource "herokux_postgres_credential" "foobar" {
postgres_id = "UUID"
name = "limited_user"
}
```
Notes:
- docs should indicate this resource should NOT be used to import the `default` credential.
> New resource: `herokux_postgres_credential`

- TESTING.md
- herokux/provider.go
- herokux/resource_herokux_data_connector.go
- herokux/resource_herokux_kafka_consumer_group.go
- herokux/resource_herokux_kafka_topic.go
- herokux/resource_herokux_postgres.go
- herokux/resource_herokux_postgres_credential.go
- herokux/resource_herokux_postgres_mtls.go
- herokux/resource_herokux_postgres_mtls_certificate.go
- herokux/resource_herokux_postgres_mtls_iprule.go
- herokux/resource_herokux_privatelink.go
- website/docs/index.html.markdown
Standardize the polling interval to 20 seconds to alleviate unnecessary calls to the APIs as most resources take time to be provisioned, deprovisioned, or modified.
This can be adjusted later on as needed.
> standardize state frequency polling multiplier

- api/postgres/postgres-accessors.go
- api/postgres/settings.go
- api/postgres/types.go
- herokux/config.go
- herokux/helpers.go
- herokux/import_herokux_postgres_settings_test.go
- herokux/provider.go
- herokux/resource_herokux_postgres_maintenance_window.go
- herokux/resource_herokux_postgres_settings.go
- herokux/resource_herokux_postgres_settings_test.go
- website/docs/index.html.markdown
- website/docs/r/data_connector.html.markdown
- website/docs/r/kafka_consumer_group.html.markdown
- website/docs/r/kafka_topic.html.markdown
- website/docs/r/postgres_credential.html.markdown
- website/docs/r/postgres_mtls.html.markdown
- website/docs/r/postgres_mtls_certificate.html.markdown
- website/docs/r/postgres_mtls_iprule.html.markdown
- website/docs/r/postgres_settings.html.markdown
- website/docs/r/privatelink.html.markdown
- website/herokux.erb
The `PATCH` endpoint doesn't check if the updates were fully committed as subsequent `PATCH` requests return a `422` with the below error:
```
{
"id": "unprocessable_entity",
"message": "Still applying previous configuration change to this database. Please try again later."
}
```
I don't see any way to loop to check if the updates were applied successfully.
> New resource: `herokux_postgres_settings`

- api/postgres/data_link.go
- api/postgres/postgres-accessors.go
- docs/resources/data_link.md
- docs/resources/shield_private_space.md
- herokux/import_herokux_data_link_test.go
- herokux/provider.go
- herokux/resource_herokux_data_link.go
- herokux/resource_herokux_data_link_test.go
https://devcenter.heroku.com/articles/heroku-data-links#:~:text=hobby%20tier%20databases.-,Overview,tables%20in%20the%20local%20database
----
`"Link name must be lowercase using, at most, 63 alphanumeric characters and start with a letter, no hyphens"`
> New resource: `herokux_postgres_datalink`.

- api/gen-accessors.go
- api/kafka/kafka-accessors.go
- api/kafka/topics.go
These fields can sometimes be the integer `0` or string encoded floats
when returned from the Heroku API.
This causes Unmarshalling to fail, using `json.Number` handles these
edge-cases.
Signed-off-by: Christian Gregg <christian@bissy.io>
> Make Topic.{BytesIn,BytesOut,MessageIn}PerSecond json.Number

- herokux/helpers.go
- herokux/resource_herokux_kafka_consumer_group.go
- herokux/resource_herokux_kafka_topic.go
Set `kafka_id` on read so that terraform is aware of its value and
doesn't force recreating the topic.
Because we currently are not setting this value if the tf file contains
a `kafka_id` terraform will try to recreate it because it has changed
from unset->set.
Signed-off-by: Christian Gregg <christian@bissy.io>
> Set kafka_id on resourceHerokuxKafkaTopicRead

- api/redis/maintenance.go
- api/redis/redis-accessors.go
- api/redis/redis.go
- herokux/provider.go
- herokux/resource_herokux_redis_maintenance_window.go
- herokux/resource_herokux_redis_maintenance_window_test.go
Implementing new resource `herokux_redis_maintenance_window` that would add the ability to set the maintenance window for Redis add-ons.
Resolves #64
> Implement new resource: `herokux_redis_maintenance_window`

- herokux/resource_herokux_postgres_backup_schedule.go
Updating the regular expression that validates the `timezone` in `herokux_postgres_backup_schedule` so it accepts underscores.
Resolves #74
> Fix timezone validation in herokux_postgres_backup_schedule

- api/metrics/formation.go
- docs/resources/formation_autoscaling.md
- herokux/helpers.go
- herokux/import_herokux_formation_autoscaling_test.go
- herokux/provider.go
- herokux/resource_herokux_app_alert.go
- herokux/resource_herokux_formation_autoscaling.go
- herokux/resource_herokux_formation_autoscaling_test.go
This PR improves and fixes the behavior of `herokux_formation_autoscaling` in the following ways:
* Deletion will now disable the autoscaling remotely and remove resource from state instead of just removing resource from state.
* Creation properly uses the correct API endpoint to create the resource. Prior behavior was to use the update API endpoint.
* Attribute renames for consistency with `heroku_formation`:
* `herokux_formation_autoscaling.dyno_type` ===> `herokux_formation_autoscaling.dyno_size`
* `herokux_formation_autoscaling.formation` ===> `herokux_formation_autoscaling.process_type`
* Documentation overhaul `herokux_formation_autoscaling`:
* Detail potential issues when using this resource.
* Update verbage to indicate a harmonious relationship with `heroku_formation`. Prior …
> Yet another fix/improvement to `herokux_formation_autoscaling`

- GNUmakefile
- api/postgres/data_connector.go
When trying to update the settings on a `herokux_data_connector` resource:
```hcl
settings = {
"time.precision.mode" = "connect"
}
```
we are getting the following error:
```
unsupported 'Body' type/value
```
I eventually traced this back through simpleresty to go-resty to 
https://github.com/go-resty/resty/blob/bcec4e0910e82afff8e1e159e83e734739e9229f/middleware.go#L460-L467
It looks like `opts` is already a pointer to `DataConnectSettings` and by taking another pointer, the `kind` variable in the above code block is of `reflect.Ptr` and it falls through to the error message I was getting. I also noticed the same thing was happening with the result. I'm using terraform `v0.13.5` and was able to build this into the modules directory and was able to successfully update the settings on our …
> Fix unsupported body type when updating settings for herokux_data_connector

- .gitignore
- GNUmakefile
- api/postgres/data_connector.go
- docs/index.md
- docs/resources/data_connector.md
- herokux/config.go
- herokux/import_herokux_data_connector_test.go
- herokux/provider.go
- herokux/resource_herokux_data_connector.go
- herokux/resource_herokux_data_connector_test.go
One not so insignificant change introduced in this PR is an easier method to import data connectors using a composite value of `APP_NAME:DATA_CONNECTOR_NAME`.
Also need to add a loop to verify data connector settings are successfully updated.
----
> Some tweaks to data connector resource

- GNUmakefile
- api/postgres/database.go
- api/postgres/types.go
- docs/index.md
- docs/resources/app_container_release.md
- docs/resources/app_github_integration.md
- docs/resources/app_webhook.md
- docs/resources/connect_mappings.md
- docs/resources/data_connector.md
- docs/resources/kafka_consumer_group.md
- docs/resources/kafka_topic.md
- docs/resources/oauth_authorization.md
- docs/resources/postgres_backup_schedule.md
- docs/resources/postgres_credential.md
- docs/resources/postgres_data_link.md
- docs/resources/postgres_maintenance_window.md
- docs/resources/postgres_mtls.md
- docs/resources/postgres_mtls_certificate.md
- docs/resources/postgres_mtls_iprule.md
- docs/resources/postgres_settings.md
- docs/resources/privatelink.md
- docs/resources/redis_config.md
- docs/resources/redis_maintenance_window.md
- helper/test/config.go
- herokux/config.go
- herokux/provider.go
- herokux/resource_herokux_postgres_credential.go
- herokux/resource_herokux_postgres_credential_test.go
It appears `herokux_postgres_credential` will fail if the HA standby is not ready/under maintenance:
```
Error: POST https://postgres-api.heroku.com/postgres/v0/databases/<UUID>/credentials: 422 {"id":"unprocessable_entity","message":"Your standby is currently undergoing maintenance, making some operations unavailable at this time. Please try again later."}
```
On initial investigation, one can create the credential after `Fork/Follow` is Available, but before `HA Status` becomes Available.
Initial solution is the wait until both statuses are 'Availabile'.
Starting at `Standard0`, forks/followers becomes available and `Premium0` is when HA becomes available.
> Handle creating PG credentials when HA standby is not ready

- api/postgres/database.go
- docs/resources/postgres_credential.md
- herokux/resource_herokux_postgres_credential.go
Even after adding a precreate verification check for `herokux_postgres_credential` (#129), it appears that was not enough:
```shell
2021/05/19 12:05:42 [DEBUG] Creating postgres credential pgcredtest-th6xnb73by on postgres 0fba372c-8cfa-4a14-813f-7551132c138d
2021/05/19 12:05:43 [WARN] Got error running Terraform: exit status 1
Error: unable to create credential on postgres 0fba372c-8cfa-4a14-813f-7551132c138d
with herokux_postgres_credential.foobar,
on terraform_plugin_test.tf line 28, in resource "herokux_postgres_credential" "foobar":
28: resource "herokux_postgres_credential" "foobar" {
POST
https://postgres-api.heroku.com/postgres/v0/databases/0fba372c-8cfa-4a14-813f-7551132c138d/credentials:
422 {"id":"unprocessable_entity","message":"Your standby is currently
undergoing …
```
> More robust handling of pg cred precreate verify

- docs/resources/formation_alert.md
- herokux/resource_herokux_formation_alert.go
The `herokux_formation_alert` documentation describes the correct `notification_frequency` argument, but the example uses `email_reminder_frequency`.
```
│ Error: Unsupported argument
│
│   on modules/heroku.tf line 366, in resource "herokux_formation_alert" "processor":
│  366:   email_reminder_frequency = 1440
│
│ An argument named "email_reminder_frequency" is not expected here.
```
N/A
> Update the 'herokux_formation_alert' example to match the documentation

- docs/data-sources/app_addons.md
- docs/resources/scheduler_job.md
- herokux/data_source_herokux_app_addons.go
- herokux/data_source_herokux_app_addons_test.go
- herokux/provider.go
Renaming the existing data source because:
1) The original intent of this data source is scoped by app.
2) Introduce a new `herokux_addons` data source that is more generic.
> Rename herokux_addons to herokux_app_addons

- api/scheduler/job.go
The  request bodies for scheduler job `Create` and `Update` are [not valid JSON:API without a `type` member.](https://jsonapi.org/format/#crud)
From [this failed atlantis apply](https://github.com/devforce/trailhead-terraform/pull/1370#issuecomment-1090355347) job:
```
Error: Unable to create schedule job for app <...>
with module.<...>.herokux_scheduler_job.job["something"],
on ../../../modules/<...>.tf line 123, in resource "herokux_scheduler_job" "job":
123: resource "herokux_scheduler_job" "job" {
POST
https://particleboard.heroku.com/apps/<...>/jobs:
400 {"errors":[{"detail":"Check out http://jsonapi.org/format/#crud for more
info.","source":{"pointer":"/data/type"},"status":"400","title":"Missing type
in data parameter"}]}
Error: Unable to create schedule job for app  <...>
with …
```
> [BUGFIX] Invalid JSON:API payload for Scheduler Jobs

- docs/resources/app_github_integration.md
- docs/resources/formation_alert.md
- docs/resources/formation_autoscaling.md
Some sample codes in resource document contains wrong argument `app` (instead of `app_id`). So this PR fixes it.
cf.
- https://registry.terraform.io/providers/heroku/heroku/latest/docs/resources/slug
- https://registry.terraform.io/providers/heroku/heroku/latest/docs/resources/pipeline_coupling
- https://registry.terraform.io/providers/heroku/heroku/latest/docs/resources/app_release
- https://registry.terraform.io/providers/heroku/heroku/latest/docs/resources/formation
N/A
> Fix sample codes about of argument `app_id`

- herokux/resource_herokux_redis_config.go
- herokux/resource_herokux_redis_maintenance_window.go
The ID for a Redis addon can now be a name string like `foo-blah-12345`, so let's allow this when setting up these resources. Took a similar approach to #375, and removed the validation.
> Support non-UUID Redis IDs
